/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package evaluacionu2;

import javax.swing.JOptionPane;

/**
 *
 * @author Victor Rodriguez
 */
public class JDepartamento extends javax.swing.JFrame {
    DepartamentoA objA = new DepartamentoA();
    Departamento objD;
    

    /**
     * Creates new form JDepartamento
     */
    public JDepartamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtc = new javax.swing.JTextField();
        txte = new javax.swing.JTextField();
        txtu = new javax.swing.JTextField();
        txtp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtpc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        cboD = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        agregar = new javax.swing.JMenuItem();
        buscar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        consulta1 = new javax.swing.JMenuItem();
        consulta2 = new javax.swing.JMenuItem();
        consulta3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CLAVE: ");

        jLabel2.setText("EXTENSION:");

        jLabel3.setText("UBICACION: ");

        jLabel4.setText("DISPONIBLE:");

        jLabel5.setText("PRECIO: ");

        jLabel6.setText("PRECIO A CONSULTAR: ");

        jLabel7.setText("SUPERFICIE (EXTENSION) A CONSULTAR: ");

        txtsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtscActionPerformed(evt);
            }
        });

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        cboD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO", "SI" }));

        jMenu1.setText("ACCIONES");

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        jMenu1.add(agregar);

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        jMenu1.add(buscar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("CONSULTAS");

        consulta1.setText("CONSULTA 1");
        consulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta1ActionPerformed(evt);
            }
        });
        jMenu2.add(consulta1);

        consulta2.setText("CONSULTA 2");
        consulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta2ActionPerformed(evt);
            }
        });
        jMenu2.add(consulta2);

        consulta3.setText("CONSULTA 3");
        consulta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consulta3ActionPerformed(evt);
            }
        });
        jMenu2.add(consulta3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtc)
                            .addComponent(txte)
                            .addComponent(txtu)
                            .addComponent(txtp, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                            .addComponent(cboD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtpc)
                            .addComponent(txtsc, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtscActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
   // int c = txtc.getText();
        int clave= Integer.parseInt(txtc.getText());
        double extension=Double.parseDouble(txte.getText());
        String ubicacion = txtu.getText();
        String disponible = (String) cboD.getSelectedItem();
        double precio= Double.parseDouble(txtp.getText());

        boolean dis;
        if ("SI".equals(disponible)) {
            dis = true;
            // t=seguro;
        } else {
           dis = false;
            //7 t=seguro;

        }

        objD = new Departamento(clave, extension, ubicacion, dis, precio);
        objD.setClave(clave);
        objD.setExtension(extension);
        objD.setUbicacion(ubicacion);
        objD.setDisponible(dis);
        objD.setPrecio(precio);
        objA.Agregar(objD);
        txtc.setText("");
        txte.setText("");
        txtu.setText("");
        txtp.setText("");
        
    }//GEN-LAST:event_agregarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        txtArea.setText("");
        int i = objA.Buscar(Integer.parseInt(txtc.getText()));
        if (i != -1) {
            txtArea.setText("");
            txtArea.append("CLAVE DEL DEPARTAMENTO : " +objA.getDepartamento(i).getClave()+ "\n");
            txtArea.append("EXTENSION: " + objA.getDepartamento(i).getExtension() + "   ");
            txtArea.append("UBICACION: " + objA.getDepartamento(i).getUbicacion() + "\n");
            txtArea.append(("PRECIO: ")+objA.getDepartamento(i).getPrecio()+"\n");
           // txtArea.append("DOMICILIO: " + objHos.getPaciente(i).getDireccion() + "\n");

            if (objA.getDepartamento(i).isDisponible()) {
                txtArea.append("DISPONIBLE : SI \n");
            } else {
                txtArea.append("DISPONIBLE : NO \n");
            }
        } else {
            JOptionPane.showMessageDialog(null, "NO EXISTEN DATOS");
            //  txtArea.append("NO EXISTE REGISTRO");

        }    
    }//GEN-LAST:event_buscarActionPerformed

    private void consulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta1ActionPerformed
        // TODO add your handling code here:
    txtArea.setText("");    
    double precio= Double.parseDouble(txtpc.getText());
    txtArea.append("DEPARTAMENTOS DISPONIBLES CON PRECIO INFERIOR :\n"+objA.conA(precio));    
    }//GEN-LAST:event_consulta1ActionPerformed

    private void consulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta2ActionPerformed
        // TODO add your handling code here:
    txtArea.setText("");    
    double extension=Double.parseDouble(txtsc.getText());    
    txtArea.append("DEPARTAMENTOS DISPONIBLES CON SUPERFICE MAYOR Y UBICACION EXCELENTE :\n"+objA.conB(extension));   
    }//GEN-LAST:event_consulta2ActionPerformed

    private void consulta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consulta3ActionPerformed
        // TODO add your handling code here:
    txtArea.setText(""); 
    txtArea.append("LISTA DEL MONTO DE LA RENTA DE TODOS LOS DEPARTAMENTOS ALQUILADOS :\n"+objA.conC());       
    }//GEN-LAST:event_consulta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDepartamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDepartamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregar;
    private javax.swing.JMenuItem buscar;
    private javax.swing.JComboBox<String> cboD;
    private javax.swing.JMenuItem consulta1;
    private javax.swing.JMenuItem consulta2;
    private javax.swing.JMenuItem consulta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtc;
    private javax.swing.JTextField txte;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtpc;
    private javax.swing.JTextField txtsc;
    private javax.swing.JTextField txtu;
    // End of variables declaration//GEN-END:variables
}
